/* elf.h against the system's: every constant, every struct's size and its fields' offsets,
 * and the info macros on sample values. generated from src/apps/moon/include/elf.h */
#include <elf.h>
#include <stddef.h>
#include "say.h"

int main(void) {
 say_n("EI_NIDENT", (long) EI_NIDENT);
 say_n("EI_MAG0", (long) EI_MAG0);
 say_n("EI_MAG1", (long) EI_MAG1);
 say_n("EI_MAG2", (long) EI_MAG2);
 say_n("EI_MAG3", (long) EI_MAG3);
 say_n("EI_CLASS", (long) EI_CLASS);
 say_n("EI_DATA", (long) EI_DATA);
 say_n("EI_VERSION", (long) EI_VERSION);
 say_n("EI_OSABI", (long) EI_OSABI);
 say_n("EI_ABIVERSION", (long) EI_ABIVERSION);
 say_n("EI_PAD", (long) EI_PAD);
 say_n("ELFMAG0", (long) ELFMAG0);
 say_n("ELFMAG1", (long) ELFMAG1);
 say_n("ELFMAG2", (long) ELFMAG2);
 say_n("ELFMAG3", (long) ELFMAG3);
 say_n("SELFMAG", (long) SELFMAG);
 say_n("ELFCLASSNONE", (long) ELFCLASSNONE);
 say_n("ELFCLASS32", (long) ELFCLASS32);
 say_n("ELFCLASS64", (long) ELFCLASS64);
 say_n("ELFDATANONE", (long) ELFDATANONE);
 say_n("ELFDATA2LSB", (long) ELFDATA2LSB);
 say_n("ELFDATA2MSB", (long) ELFDATA2MSB);
 say_n("EV_NONE", (long) EV_NONE);
 say_n("EV_CURRENT", (long) EV_CURRENT);
 say_n("ELFOSABI_NONE", (long) ELFOSABI_NONE);
 say_n("ELFOSABI_SYSV", (long) ELFOSABI_SYSV);
 say_n("ELFOSABI_NETBSD", (long) ELFOSABI_NETBSD);
 say_n("ELFOSABI_GNU", (long) ELFOSABI_GNU);
 say_n("ELFOSABI_LINUX", (long) ELFOSABI_LINUX);
 say_n("ELFOSABI_FREEBSD", (long) ELFOSABI_FREEBSD);
 say_n("ET_NONE", (long) ET_NONE);
 say_n("ET_REL", (long) ET_REL);
 say_n("ET_EXEC", (long) ET_EXEC);
 say_n("ET_DYN", (long) ET_DYN);
 say_n("ET_CORE", (long) ET_CORE);
 say_n("EM_NONE", (long) EM_NONE);
 say_n("EM_SPARC", (long) EM_SPARC);
 say_n("EM_386", (long) EM_386);
 say_n("EM_68K", (long) EM_68K);
 say_n("EM_MIPS", (long) EM_MIPS);
 say_n("EM_PARISC", (long) EM_PARISC);
 say_n("EM_SPARC32PLUS", (long) EM_SPARC32PLUS);
 say_n("EM_PPC", (long) EM_PPC);
 say_n("EM_PPC64", (long) EM_PPC64);
 say_n("EM_S390", (long) EM_S390);
 say_n("EM_ARM", (long) EM_ARM);
 say_n("EM_SH", (long) EM_SH);
 say_n("EM_SPARCV9", (long) EM_SPARCV9);
 say_n("EM_IA_64", (long) EM_IA_64);
 say_n("EM_X86_64", (long) EM_X86_64);
 say_n("EM_ARC_COMPACT", (long) EM_ARC_COMPACT);
 say_n("EM_XTENSA", (long) EM_XTENSA);
 say_n("EM_AARCH64", (long) EM_AARCH64);
 say_n("EM_MICROBLAZE", (long) EM_MICROBLAZE);
 say_n("EM_ARCV2", (long) EM_ARCV2);
 say_n("EM_RISCV", (long) EM_RISCV);
 say_n("EM_BPF", (long) EM_BPF);
 say_n("EM_LOONGARCH", (long) EM_LOONGARCH);
 say_n("SHN_UNDEF", (long) SHN_UNDEF);
 say_n("SHN_LORESERVE", (long) SHN_LORESERVE);
 say_n("SHN_LOPROC", (long) SHN_LOPROC);
 say_n("SHN_HIPROC", (long) SHN_HIPROC);
 say_n("SHN_ABS", (long) SHN_ABS);
 say_n("SHN_COMMON", (long) SHN_COMMON);
 say_n("SHN_XINDEX", (long) SHN_XINDEX);
 say_n("SHN_HIRESERVE", (long) SHN_HIRESERVE);
 say_n("SHT_NULL", (long) SHT_NULL);
 say_n("SHT_PROGBITS", (long) SHT_PROGBITS);
 say_n("SHT_SYMTAB", (long) SHT_SYMTAB);
 say_n("SHT_STRTAB", (long) SHT_STRTAB);
 say_n("SHT_RELA", (long) SHT_RELA);
 say_n("SHT_HASH", (long) SHT_HASH);
 say_n("SHT_DYNAMIC", (long) SHT_DYNAMIC);
 say_n("SHT_NOTE", (long) SHT_NOTE);
 say_n("SHT_NOBITS", (long) SHT_NOBITS);
 say_n("SHT_REL", (long) SHT_REL);
 say_n("SHT_SHLIB", (long) SHT_SHLIB);
 say_n("SHT_DYNSYM", (long) SHT_DYNSYM);
 say_n("SHT_INIT_ARRAY", (long) SHT_INIT_ARRAY);
 say_n("SHT_FINI_ARRAY", (long) SHT_FINI_ARRAY);
 say_n("SHT_PREINIT_ARRAY", (long) SHT_PREINIT_ARRAY);
 say_n("SHT_GROUP", (long) SHT_GROUP);
 say_n("SHT_SYMTAB_SHNDX", (long) SHT_SYMTAB_SHNDX);
 say_n("SHT_GNU_HASH", (long) SHT_GNU_HASH);
 say_n("SHT_GNU_verdef", (long) SHT_GNU_verdef);
 say_n("SHT_GNU_verneed", (long) SHT_GNU_verneed);
 say_n("SHT_GNU_versym", (long) SHT_GNU_versym);
 say_n("SHT_LOPROC", (long) SHT_LOPROC);
 say_n("SHT_HIPROC", (long) SHT_HIPROC);
 say_n("SHT_LOUSER", (long) SHT_LOUSER);
 say_n("SHT_HIUSER", (long) SHT_HIUSER);
 say_n("SHF_WRITE", (long) SHF_WRITE);
 say_n("SHF_ALLOC", (long) SHF_ALLOC);
 say_n("SHF_EXECINSTR", (long) SHF_EXECINSTR);
 say_n("SHF_MERGE", (long) SHF_MERGE);
 say_n("SHF_STRINGS", (long) SHF_STRINGS);
 say_n("SHF_INFO_LINK", (long) SHF_INFO_LINK);
 say_n("SHF_LINK_ORDER", (long) SHF_LINK_ORDER);
 say_n("SHF_OS_NONCONFORMING", (long) SHF_OS_NONCONFORMING);
 say_n("SHF_GROUP", (long) SHF_GROUP);
 say_n("SHF_TLS", (long) SHF_TLS);
 say_n("SHF_COMPRESSED", (long) SHF_COMPRESSED);
 say_n("SHF_MASKPROC", (long) SHF_MASKPROC);
 say_n("GRP_COMDAT", (long) GRP_COMDAT);
 say_n("STB_LOCAL", (long) STB_LOCAL);
 say_n("STB_GLOBAL", (long) STB_GLOBAL);
 say_n("STB_WEAK", (long) STB_WEAK);
 say_n("STB_LOPROC", (long) STB_LOPROC);
 say_n("STB_HIPROC", (long) STB_HIPROC);
 say_n("STT_NOTYPE", (long) STT_NOTYPE);
 say_n("STT_OBJECT", (long) STT_OBJECT);
 say_n("STT_FUNC", (long) STT_FUNC);
 say_n("STT_SECTION", (long) STT_SECTION);
 say_n("STT_FILE", (long) STT_FILE);
 say_n("STT_COMMON", (long) STT_COMMON);
 say_n("STT_TLS", (long) STT_TLS);
 say_n("STT_LOPROC", (long) STT_LOPROC);
 say_n("STT_HIPROC", (long) STT_HIPROC);
 say_n("STT_SPARC_REGISTER", (long) STT_SPARC_REGISTER);
 say_n("STV_DEFAULT", (long) STV_DEFAULT);
 say_n("STV_INTERNAL", (long) STV_INTERNAL);
 say_n("STV_HIDDEN", (long) STV_HIDDEN);
 say_n("STV_PROTECTED", (long) STV_PROTECTED);
 say_n("R_386_NONE", (long) R_386_NONE);
 say_n("R_386_32", (long) R_386_32);
 say_n("R_386_PC32", (long) R_386_PC32);
 say_n("R_X86_64_NONE", (long) R_X86_64_NONE);
 say_n("R_X86_64_64", (long) R_X86_64_64);
 say_n("R_X86_64_PC32", (long) R_X86_64_PC32);
 say_n("R_X86_64_PLT32", (long) R_X86_64_PLT32);
 say_n("R_X86_64_32", (long) R_X86_64_32);
 say_n("R_X86_64_32S", (long) R_X86_64_32S);
 say_n("R_X86_64_PC64", (long) R_X86_64_PC64);
 say_n("R_ARM_NONE", (long) R_ARM_NONE);
 say_n("R_ARM_PC24", (long) R_ARM_PC24);
 say_n("R_ARM_ABS32", (long) R_ARM_ABS32);
 say_n("R_ARM_REL32", (long) R_ARM_REL32);
 say_n("R_ARM_THM_PC22", (long) R_ARM_THM_PC22);
 say_n("R_ARM_CALL", (long) R_ARM_CALL);
 say_n("R_ARM_JUMP24", (long) R_ARM_JUMP24);
 say_n("R_ARM_THM_JUMP24", (long) R_ARM_THM_JUMP24);
 say_n("R_ARM_MOVW_ABS_NC", (long) R_ARM_MOVW_ABS_NC);
 say_n("R_ARM_MOVT_ABS", (long) R_ARM_MOVT_ABS);
 say_n("R_ARM_THM_MOVW_ABS_NC", (long) R_ARM_THM_MOVW_ABS_NC);
 say_n("R_ARM_THM_MOVT_ABS", (long) R_ARM_THM_MOVT_ABS);
 say_n("R_ARM_THM_JUMP19", (long) R_ARM_THM_JUMP19);
 say_n("R_AARCH64_NONE", (long) R_AARCH64_NONE);
 say_n("R_AARCH64_ABS64", (long) R_AARCH64_ABS64);
 say_n("R_AARCH64_ABS32", (long) R_AARCH64_ABS32);
 say_n("R_AARCH64_PREL64", (long) R_AARCH64_PREL64);
 say_n("R_AARCH64_PREL32", (long) R_AARCH64_PREL32);
 say_n("R_AARCH64_JUMP26", (long) R_AARCH64_JUMP26);
 say_n("R_AARCH64_CALL26", (long) R_AARCH64_CALL26);
 say_n("R_MIPS_NONE", (long) R_MIPS_NONE);
 say_n("R_MIPS_32", (long) R_MIPS_32);
 say_n("R_MIPS_26", (long) R_MIPS_26);
 say_n("R_MIPS_HI16", (long) R_MIPS_HI16);
 say_n("R_MIPS_LO16", (long) R_MIPS_LO16);
 say_n("R_RISCV_NONE", (long) R_RISCV_NONE);
 say_n("R_RISCV_32", (long) R_RISCV_32);
 say_n("R_RISCV_64", (long) R_RISCV_64);
 say_n("R_RISCV_SUB32", (long) R_RISCV_SUB32);
 say_n("R_LARCH_SUB32", (long) R_LARCH_SUB32);
 say_n("R_LARCH_RELAX", (long) R_LARCH_RELAX);
 say_n("R_LARCH_ALIGN", (long) R_LARCH_ALIGN);
 say_n("PT_NULL", (long) PT_NULL);
 say_n("PT_LOAD", (long) PT_LOAD);
 say_n("PT_DYNAMIC", (long) PT_DYNAMIC);
 say_n("PT_INTERP", (long) PT_INTERP);
 say_n("PT_NOTE", (long) PT_NOTE);
 say_n("PT_SHLIB", (long) PT_SHLIB);
 say_n("PT_PHDR", (long) PT_PHDR);
 say_n("PT_TLS", (long) PT_TLS);
 say_n("PT_GNU_EH_FRAME", (long) PT_GNU_EH_FRAME);
 say_n("PT_GNU_STACK", (long) PT_GNU_STACK);
 say_n("PT_GNU_RELRO", (long) PT_GNU_RELRO);
 say_n("PF_X", (long) PF_X);
 say_n("PF_W", (long) PF_W);
 say_n("PF_R", (long) PF_R);
 say_n("DT_NULL", (long) DT_NULL);
 say_n("DT_NEEDED", (long) DT_NEEDED);
 say_n("DT_PLTRELSZ", (long) DT_PLTRELSZ);
 say_n("DT_PLTGOT", (long) DT_PLTGOT);
 say_n("DT_HASH", (long) DT_HASH);
 say_n("DT_STRTAB", (long) DT_STRTAB);
 say_n("DT_SYMTAB", (long) DT_SYMTAB);
 say_n("DT_RELA", (long) DT_RELA);
 say_n("DT_RELASZ", (long) DT_RELASZ);
 say_n("DT_RELAENT", (long) DT_RELAENT);
 say_n("DT_STRSZ", (long) DT_STRSZ);
 say_n("DT_SYMENT", (long) DT_SYMENT);
 say_n("DT_INIT", (long) DT_INIT);
 say_n("DT_FINI", (long) DT_FINI);
 say_n("DT_SONAME", (long) DT_SONAME);
 say_n("DT_RPATH", (long) DT_RPATH);
 say_n("DT_SYMBOLIC", (long) DT_SYMBOLIC);
 say_n("DT_REL", (long) DT_REL);
 say_n("DT_RELSZ", (long) DT_RELSZ);
 say_n("DT_RELENT", (long) DT_RELENT);
 say_n("DT_PLTREL", (long) DT_PLTREL);
 say_n("DT_DEBUG", (long) DT_DEBUG);
 say_n("DT_TEXTREL", (long) DT_TEXTREL);
 say_n("DT_JMPREL", (long) DT_JMPREL);
 say_n("NT_PRSTATUS", (long) NT_PRSTATUS);
 say_n("NT_GNU_ABI_TAG", (long) NT_GNU_ABI_TAG);
 say_n("NT_GNU_BUILD_ID", (long) NT_GNU_BUILD_ID);
 say_n("sizeof Elf32_Ehdr", (long) sizeof(Elf32_Ehdr));
 say_n("  Elf32_Ehdr.e_ident", (long) offsetof(Elf32_Ehdr, e_ident));
 say_n("  Elf32_Ehdr.e_type", (long) offsetof(Elf32_Ehdr, e_type));
 say_n("  Elf32_Ehdr.e_machine", (long) offsetof(Elf32_Ehdr, e_machine));
 say_n("  Elf32_Ehdr.e_version", (long) offsetof(Elf32_Ehdr, e_version));
 say_n("  Elf32_Ehdr.e_entry", (long) offsetof(Elf32_Ehdr, e_entry));
 say_n("  Elf32_Ehdr.e_phoff", (long) offsetof(Elf32_Ehdr, e_phoff));
 say_n("  Elf32_Ehdr.e_shoff", (long) offsetof(Elf32_Ehdr, e_shoff));
 say_n("  Elf32_Ehdr.e_flags", (long) offsetof(Elf32_Ehdr, e_flags));
 say_n("  Elf32_Ehdr.e_ehsize", (long) offsetof(Elf32_Ehdr, e_ehsize));
 say_n("  Elf32_Ehdr.e_phentsize", (long) offsetof(Elf32_Ehdr, e_phentsize));
 say_n("  Elf32_Ehdr.e_phnum", (long) offsetof(Elf32_Ehdr, e_phnum));
 say_n("  Elf32_Ehdr.e_shentsize", (long) offsetof(Elf32_Ehdr, e_shentsize));
 say_n("  Elf32_Ehdr.e_shnum", (long) offsetof(Elf32_Ehdr, e_shnum));
 say_n("  Elf32_Ehdr.e_shstrndx", (long) offsetof(Elf32_Ehdr, e_shstrndx));
 say_n("sizeof Elf64_Ehdr", (long) sizeof(Elf64_Ehdr));
 say_n("  Elf64_Ehdr.e_ident", (long) offsetof(Elf64_Ehdr, e_ident));
 say_n("  Elf64_Ehdr.e_type", (long) offsetof(Elf64_Ehdr, e_type));
 say_n("  Elf64_Ehdr.e_machine", (long) offsetof(Elf64_Ehdr, e_machine));
 say_n("  Elf64_Ehdr.e_version", (long) offsetof(Elf64_Ehdr, e_version));
 say_n("  Elf64_Ehdr.e_entry", (long) offsetof(Elf64_Ehdr, e_entry));
 say_n("  Elf64_Ehdr.e_phoff", (long) offsetof(Elf64_Ehdr, e_phoff));
 say_n("  Elf64_Ehdr.e_shoff", (long) offsetof(Elf64_Ehdr, e_shoff));
 say_n("  Elf64_Ehdr.e_flags", (long) offsetof(Elf64_Ehdr, e_flags));
 say_n("  Elf64_Ehdr.e_ehsize", (long) offsetof(Elf64_Ehdr, e_ehsize));
 say_n("  Elf64_Ehdr.e_phentsize", (long) offsetof(Elf64_Ehdr, e_phentsize));
 say_n("  Elf64_Ehdr.e_phnum", (long) offsetof(Elf64_Ehdr, e_phnum));
 say_n("  Elf64_Ehdr.e_shentsize", (long) offsetof(Elf64_Ehdr, e_shentsize));
 say_n("  Elf64_Ehdr.e_shnum", (long) offsetof(Elf64_Ehdr, e_shnum));
 say_n("  Elf64_Ehdr.e_shstrndx", (long) offsetof(Elf64_Ehdr, e_shstrndx));
 say_n("sizeof Elf32_Shdr", (long) sizeof(Elf32_Shdr));
 say_n("  Elf32_Shdr.sh_name", (long) offsetof(Elf32_Shdr, sh_name));
 say_n("  Elf32_Shdr.sh_type", (long) offsetof(Elf32_Shdr, sh_type));
 say_n("  Elf32_Shdr.sh_flags", (long) offsetof(Elf32_Shdr, sh_flags));
 say_n("  Elf32_Shdr.sh_addr", (long) offsetof(Elf32_Shdr, sh_addr));
 say_n("  Elf32_Shdr.sh_offset", (long) offsetof(Elf32_Shdr, sh_offset));
 say_n("  Elf32_Shdr.sh_size", (long) offsetof(Elf32_Shdr, sh_size));
 say_n("  Elf32_Shdr.sh_link", (long) offsetof(Elf32_Shdr, sh_link));
 say_n("  Elf32_Shdr.sh_info", (long) offsetof(Elf32_Shdr, sh_info));
 say_n("  Elf32_Shdr.sh_addralign", (long) offsetof(Elf32_Shdr, sh_addralign));
 say_n("  Elf32_Shdr.sh_entsize", (long) offsetof(Elf32_Shdr, sh_entsize));
 say_n("sizeof Elf64_Shdr", (long) sizeof(Elf64_Shdr));
 say_n("  Elf64_Shdr.sh_name", (long) offsetof(Elf64_Shdr, sh_name));
 say_n("  Elf64_Shdr.sh_type", (long) offsetof(Elf64_Shdr, sh_type));
 say_n("  Elf64_Shdr.sh_flags", (long) offsetof(Elf64_Shdr, sh_flags));
 say_n("  Elf64_Shdr.sh_addr", (long) offsetof(Elf64_Shdr, sh_addr));
 say_n("  Elf64_Shdr.sh_offset", (long) offsetof(Elf64_Shdr, sh_offset));
 say_n("  Elf64_Shdr.sh_size", (long) offsetof(Elf64_Shdr, sh_size));
 say_n("  Elf64_Shdr.sh_link", (long) offsetof(Elf64_Shdr, sh_link));
 say_n("  Elf64_Shdr.sh_info", (long) offsetof(Elf64_Shdr, sh_info));
 say_n("  Elf64_Shdr.sh_addralign", (long) offsetof(Elf64_Shdr, sh_addralign));
 say_n("  Elf64_Shdr.sh_entsize", (long) offsetof(Elf64_Shdr, sh_entsize));
 say_n("sizeof Elf32_Sym", (long) sizeof(Elf32_Sym));
 say_n("  Elf32_Sym.st_name", (long) offsetof(Elf32_Sym, st_name));
 say_n("  Elf32_Sym.st_value", (long) offsetof(Elf32_Sym, st_value));
 say_n("  Elf32_Sym.st_size", (long) offsetof(Elf32_Sym, st_size));
 say_n("  Elf32_Sym.st_info", (long) offsetof(Elf32_Sym, st_info));
 say_n("  Elf32_Sym.st_other", (long) offsetof(Elf32_Sym, st_other));
 say_n("  Elf32_Sym.st_shndx", (long) offsetof(Elf32_Sym, st_shndx));
 say_n("sizeof Elf64_Sym", (long) sizeof(Elf64_Sym));
 say_n("  Elf64_Sym.st_name", (long) offsetof(Elf64_Sym, st_name));
 say_n("  Elf64_Sym.st_info", (long) offsetof(Elf64_Sym, st_info));
 say_n("  Elf64_Sym.st_other", (long) offsetof(Elf64_Sym, st_other));
 say_n("  Elf64_Sym.st_shndx", (long) offsetof(Elf64_Sym, st_shndx));
 say_n("  Elf64_Sym.st_value", (long) offsetof(Elf64_Sym, st_value));
 say_n("  Elf64_Sym.st_size", (long) offsetof(Elf64_Sym, st_size));
 say_n("sizeof Elf32_Rel", (long) sizeof(Elf32_Rel));
 say_n("  Elf32_Rel.r_offset", (long) offsetof(Elf32_Rel, r_offset));
 say_n("  Elf32_Rel.r_info", (long) offsetof(Elf32_Rel, r_info));
 say_n("sizeof Elf32_Rela", (long) sizeof(Elf32_Rela));
 say_n("  Elf32_Rela.r_offset", (long) offsetof(Elf32_Rela, r_offset));
 say_n("  Elf32_Rela.r_info", (long) offsetof(Elf32_Rela, r_info));
 say_n("  Elf32_Rela.r_addend", (long) offsetof(Elf32_Rela, r_addend));
 say_n("sizeof Elf64_Rel", (long) sizeof(Elf64_Rel));
 say_n("  Elf64_Rel.r_offset", (long) offsetof(Elf64_Rel, r_offset));
 say_n("  Elf64_Rel.r_info", (long) offsetof(Elf64_Rel, r_info));
 say_n("sizeof Elf64_Rela", (long) sizeof(Elf64_Rela));
 say_n("  Elf64_Rela.r_offset", (long) offsetof(Elf64_Rela, r_offset));
 say_n("  Elf64_Rela.r_info", (long) offsetof(Elf64_Rela, r_info));
 say_n("  Elf64_Rela.r_addend", (long) offsetof(Elf64_Rela, r_addend));
 say_n("sizeof Elf32_Phdr", (long) sizeof(Elf32_Phdr));
 say_n("  Elf32_Phdr.p_type", (long) offsetof(Elf32_Phdr, p_type));
 say_n("  Elf32_Phdr.p_offset", (long) offsetof(Elf32_Phdr, p_offset));
 say_n("  Elf32_Phdr.p_vaddr", (long) offsetof(Elf32_Phdr, p_vaddr));
 say_n("  Elf32_Phdr.p_paddr", (long) offsetof(Elf32_Phdr, p_paddr));
 say_n("  Elf32_Phdr.p_filesz", (long) offsetof(Elf32_Phdr, p_filesz));
 say_n("  Elf32_Phdr.p_memsz", (long) offsetof(Elf32_Phdr, p_memsz));
 say_n("  Elf32_Phdr.p_flags", (long) offsetof(Elf32_Phdr, p_flags));
 say_n("  Elf32_Phdr.p_align", (long) offsetof(Elf32_Phdr, p_align));
 say_n("sizeof Elf64_Phdr", (long) sizeof(Elf64_Phdr));
 say_n("  Elf64_Phdr.p_type", (long) offsetof(Elf64_Phdr, p_type));
 say_n("  Elf64_Phdr.p_flags", (long) offsetof(Elf64_Phdr, p_flags));
 say_n("  Elf64_Phdr.p_offset", (long) offsetof(Elf64_Phdr, p_offset));
 say_n("  Elf64_Phdr.p_vaddr", (long) offsetof(Elf64_Phdr, p_vaddr));
 say_n("  Elf64_Phdr.p_paddr", (long) offsetof(Elf64_Phdr, p_paddr));
 say_n("  Elf64_Phdr.p_filesz", (long) offsetof(Elf64_Phdr, p_filesz));
 say_n("  Elf64_Phdr.p_memsz", (long) offsetof(Elf64_Phdr, p_memsz));
 say_n("  Elf64_Phdr.p_align", (long) offsetof(Elf64_Phdr, p_align));
 say_n("sizeof Elf32_Dyn", (long) sizeof(Elf32_Dyn));
 say_n("  Elf32_Dyn.d_tag", (long) offsetof(Elf32_Dyn, d_tag));
 say_n("  Elf32_Dyn.d_un", (long) offsetof(Elf32_Dyn, d_un));
 say_n("sizeof Elf64_Dyn", (long) sizeof(Elf64_Dyn));
 say_n("  Elf64_Dyn.d_tag", (long) offsetof(Elf64_Dyn, d_tag));
 say_n("  Elf64_Dyn.d_un", (long) offsetof(Elf64_Dyn, d_un));
 say_n("sizeof Elf32_Nhdr", (long) sizeof(Elf32_Nhdr));
 say_n("  Elf32_Nhdr.n_namesz", (long) offsetof(Elf32_Nhdr, n_namesz));
 say_n("  Elf32_Nhdr.n_descsz", (long) offsetof(Elf32_Nhdr, n_descsz));
 say_n("  Elf32_Nhdr.n_type", (long) offsetof(Elf32_Nhdr, n_type));
 say_n("sizeof Elf64_Nhdr", (long) sizeof(Elf64_Nhdr));
 say_n("  Elf64_Nhdr.n_namesz", (long) offsetof(Elf64_Nhdr, n_namesz));
 say_n("  Elf64_Nhdr.n_descsz", (long) offsetof(Elf64_Nhdr, n_descsz));
 say_n("  Elf64_Nhdr.n_type", (long) offsetof(Elf64_Nhdr, n_type));
 say_n("EF_ARM_EABIMASK", (long) EF_ARM_EABIMASK);
 say_n("EF_ARM_EABI_UNKNOWN", (long) EF_ARM_EABI_UNKNOWN);
 say_n("EF_ARM_EABI_VER4", (long) EF_ARM_EABI_VER4);
 say_n("EF_ARM_EABI_VER5", (long) EF_ARM_EABI_VER5);
 say_n("EF_ARM_ABI_FLOAT_SOFT", (long) EF_ARM_ABI_FLOAT_SOFT);
 say_n("EF_ARM_ABI_FLOAT_HARD", (long) EF_ARM_ABI_FLOAT_HARD);
 say_n("EF_ARM_LE8", (long) EF_ARM_LE8);
 say_n("EF_ARM_BE8", (long) EF_ARM_BE8);
 say_n("EF_ARM_EABI_VERSION", (long) EF_ARM_EABI_VERSION(0x05000402u));
 say_s("ELFMAG", ELFMAG); say_n("SELFMAG", SELFMAG);
 say_n("ELF32_ST_BIND", (long) ELF32_ST_BIND(0x21)); say_n("ELF32_ST_TYPE", (long) ELF32_ST_TYPE(0x21)); say_n("ELF32_ST_INFO", (long) ELF32_ST_INFO(2, 1));
 say_n("ELF32_ST_VISIBILITY", (long) ELF32_ST_VISIBILITY(0x13));
 say_n("ELF64_ST_BIND", (long) ELF64_ST_BIND(0x21)); say_n("ELF64_ST_TYPE", (long) ELF64_ST_TYPE(0x21)); say_n("ELF64_ST_INFO", (long) ELF64_ST_INFO(2, 1));
 say_n("ELF64_ST_VISIBILITY", (long) ELF64_ST_VISIBILITY(0x13));
 say_n("ELF32_R_SYM", (long) ELF32_R_SYM(0x1234u)); say_n("ELF32_R_TYPE", (long) ELF32_R_TYPE(0x1234u)); say_n("ELF32_R_INFO", (long) ELF32_R_INFO(0x12u, 0x34u));
 say_n("ELF64_R_SYM", (long) ELF64_R_SYM(0x500000007ull)); say_n("ELF64_R_TYPE", (long) ELF64_R_TYPE(0x500000007ull)); say_n("ELF64_R_INFO.hi", (long) (ELF64_R_INFO(5ull, 7ull) >> 32));
 return 0; }
