#lang racket/base
;; Bell numbers in base 36 (see bench/benches/bell.l) -- a bignum-tower stress.
(require "../lib/bench.rkt")
(define digits "0123456789abcdefghijklmnopqrstuvwxyz")
(define base (string-length digits))
(define (bell-run limit)
  (let ([facts (make-hash)] [bells (make-hash)])
    (define (fact n)
      (or (hash-ref facts n #f)
          (let loop ([x 1] [m n])
            (if (> m 1) (loop (* x m) (- m 1)) (begin (hash-set! facts n x) x)))))
    (define (choose n k) (/ (fact n) (* (fact k) (fact (- n k)))))
    (define (bell n)
      (or (hash-ref bells n #f)
          (let ([r (if (< n 2) 1
                       (let loop ([k 0] [a 0])
                         (if (< k n) (loop (+ k 1) (+ a (* (choose (- n 1) k) (bell k)))) a)))])
            (hash-set! bells n r) r)))
    (define (show n)
      (let loop ([n n] [s ""])
        (if (> n 0)
            (loop (quotient n base)
                  (string-append (string (string-ref digits (remainder n base))) s))
            s)))
    (let loop ([i 0] [total 0])
      (let ([b (show (bell i))])
        (if (> (string-length b) limit) total (loop (+ i 1) (+ total (string-length b))))))))
(bench "bell" (lambda () (bell-run 280)))
