(load "lib/bench.lisp")
(defparameter *n* 100000)
(defparameter *m* 1000000007)
(defun twice (f) (lambda (x) (funcall f (funcall f x))))
(defun adder (i) (lambda (x) (+ x i)))
(bench "closure"
  (lambda ()
    (let ((acc 0))
      (dotimes (i *n*) (setf acc (mod (+ (* acc 31) (funcall (twice (adder i)) i)) *m*)))
      acc)))
