// mx.h -- +/* dispatch matrices. generated by mx.l, do not edit
// a row names its lanes: every numeric kind, then mint nom string chain tablet hot
#define mx_row(num, mint, nom, str, chain, tab, hot) { \
 [KMint] = mint, [KNom] = nom, [KCharm] = num, [KSun] = num, [KGem] = num, \
 [KTwin] = num, [KTrayZ] = num, [KTrayR] = num, [KTrayC] = num, [KTrayO] = num, \
 [KString] = str, [KChain] = chain, [KTablet] = tab, [KHot] = hot, }
#define mx_ADD_MINT mx_row(lvm_bin_unit, lvm_bin_unit, lvm_bin_unit, lvm_bin_unit, lvm_bin_unit, lvm_bin_unit, lvm_bin_unit)
#define mx_ADD_NUM mx_row(lvm_addn, lvm_bin_unit, lvm_bin_unit, lvm_bin_b, lvm_bin_b, lvm_addh, lvm_addh)
#define mx_ADD_STR mx_row(lvm_bin_a, lvm_bin_unit, lvm_bin_unit, lvm_add_string, lvm_add_seq, lvm_addh, lvm_addh)
#define mx_ADD_TWO mx_row(lvm_bin_a, lvm_bin_unit, lvm_bin_unit, lvm_add_seq, lvm_add_seq, lvm_addh, lvm_addh)
#define mx_ADD_H mx_row(lvm_addh, lvm_bin_unit, lvm_bin_unit, lvm_addh, lvm_addh, lvm_addh, lvm_addh)
#define mx_MUL_MINT mx_row(lvm_0, lvm_0, lvm_0, lvm_0, lvm_0, lvm_0, lvm_0)
#define mx_MUL_NUM mx_row(lvm_muln, lvm_0, lvm_0, lvm_mul_rep, lvm_mul_rep, lvm_mulh, lvm_mulh)
#define mx_MUL_REP mx_row(lvm_mul_rep, lvm_0, lvm_0, lvm_0, lvm_0, lvm_mulh, lvm_mulh)
#define mx_MUL_CHAIN mx_row(lvm_mul_rep, lvm_0, lvm_0, lvm_0, lvm_mul_cart, lvm_mulh, lvm_mulh)
#define mx_MUL_H mx_row(lvm_mulh, lvm_0, lvm_0, lvm_mulh, lvm_mulh, lvm_mulh, lvm_mulh)
static lvm_t *const ai_add_mx[KN][KN] = {
 [KMint] = mx_ADD_MINT,
 [KNom] = mx_ADD_MINT,
 [KCharm] = mx_ADD_NUM,
 [KSun] = mx_ADD_NUM,
 [KGem] = mx_ADD_NUM,
 [KTwin] = mx_ADD_NUM,
 [KTrayZ] = mx_ADD_NUM,
 [KTrayR] = mx_ADD_NUM,
 [KTrayC] = mx_ADD_NUM,
 [KTrayO] = mx_ADD_NUM,
 [KString] = mx_ADD_STR,
 [KChain] = mx_ADD_TWO,
 [KTablet] = mx_ADD_H,
 [KHot] = mx_ADD_H,
};
static lvm_t *const ai_mul_mx[KN][KN] = {
 [KMint] = mx_MUL_MINT,
 [KNom] = mx_MUL_MINT,
 [KCharm] = mx_MUL_NUM,
 [KSun] = mx_MUL_NUM,
 [KGem] = mx_MUL_NUM,
 [KTwin] = mx_MUL_NUM,
 [KTrayZ] = mx_MUL_NUM,
 [KTrayR] = mx_MUL_NUM,
 [KTrayC] = mx_MUL_NUM,
 [KTrayO] = mx_MUL_NUM,
 [KString] = mx_MUL_REP,
 [KChain] = mx_MUL_CHAIN,
 [KTablet] = mx_MUL_H,
 [KHot] = mx_MUL_H,
};
static enum q const ai_kind_of_d[] = { [DMint] = KMint, [DNom] = KNom, [DGem] = KGem, [DTwin] = KTwin, [DBig] = KSun, [DTray] = KTrayZ, [DString] = KString, [DChain] = KChain };
#undef mx_row
#undef mx_ADD_MINT
#undef mx_ADD_NUM
#undef mx_ADD_STR
#undef mx_ADD_TWO
#undef mx_ADD_H
#undef mx_MUL_MINT
#undef mx_MUL_NUM
#undef mx_MUL_REP
#undef mx_MUL_CHAIN
#undef mx_MUL_H
