// nifs.h -- the nif + instruction registry. generated by nifs.l, do not edit
// one row per nif: P(at, name, impl, mod) plain, C(at, arity, name, impl, mod) curried
#define nif_rows(P, C) \
 P(0, "clock", lvm_clock, 0) \
 P(2, "nclock", lvm_nclock, 0) \
 P(4, "please", lvm_please, 0) \
 P(6, "gauge", lvm_gauge, 0) \
 P(8, "tune", lvm_tune, 0) \
 P(10, "apof", lvm_apof, 0) \
 C(12, 2, "seal-hook", lvm_seal, 0) \
 P(16, "heard", lvm_heard, 0) \
 P(18, "worn", lvm_worn, 0) \
 P(20, "myself", lvm_myself, 0) \
 P(22, "stack", lvm_stack, 0) \
 P(24, "setstack", lvm_setstack, 0) \
 P(26, "lib", lvm_lib, 0) \
 P(28, "kreg", lvm_kreg, 0) \
 C(30, 2, "+", lvm_add, 0) \
 C(34, 2, "-", lvm_sub, 0) \
 C(38, 2, "*", lvm_mul, 0) \
 C(42, 2, "/", lvm_quot, 0) \
 C(46, 2, "//", lvm_fquot, 0) \
 C(50, 2, "%", lvm_rem, 0) \
 C(54, 2, "<", lvm_lt, 0) \
 C(58, 2, "<=", lvm_le, 0) \
 C(62, 2, "=", lvm_eq, 0) \
 C(66, 2, ">=", lvm_ge, 0) \
 C(70, 2, ">", lvm_gt, 0) \
 C(74, 2, "==", lvm_same, 0) \
 C(78, 2, "elem", lvm_elem, 0) \
 C(82, 2, "eleq", lvm_eleq, 0) \
 C(86, 2, "<<", lvm_bsl, 0) \
 C(90, 2, ">>", lvm_bsr, 0) \
 C(94, 2, "&", lvm_band, 0) \
 C(98, 2, "|", lvm_bor, 0) \
 C(102, 2, "^", lvm_bxor, 0) \
 C(106, 2, ".", lvm_link, 0) \
 P(110, "cap", lvm_cap, 0) \
 P(112, "cup", lvm_cup, 0) \
 P(114, "sort", lvm_sort, 0) \
 C(116, 2, "sortby", lvm_sortby, 0) \
 P(120, "tally", lvm_tally, 0) \
 C(122, 2, "long?", lvm_longp, 0) \
 C(126, 3, "snip", lvm_snip, 0) \
 P(130, "sound", lvm_sound, 0) \
 P(132, "sounds", lvm_sounds, 0) \
 P(134, "string", lvm_string, 0) \
 P(136, "nom", lvm_nomctor, 0) \
 P(138, "spin", lvm_spin, 0) \
 C(140, 2, "peek", lvm_peek, 0) \
 P(144, "nifnom", lvm_nifnom, 0) \
 C(146, 3, "poke", lvm_poke, 0) \
 C(150, 2, "pick", lvm_pick, 0) \
 C(154, 3, "place", lvm_place, 0) \
 P(158, "trim", lvm_trim, 0) \
 C(160, 2, "seek", lvm_seek, 0) \
 C(164, 4, "thrun", lvm_thrun, 0) \
 P(168, "stem", lvm_stem, 0) \
 P(170, "span", lvm_span, 0) \
 P(172, "sat", lvm_saturate, 0) \
 P(174, "ceil", lvm_ceil, 0) \
 C(176, 3, "peep", lvm_peep, 0) \
 C(180, 3, "pin", lvm_pin, 0) \
 C(184, 3, "pull", lvm_pull, 0) \
 P(188, "tablet", lvm_tablet, 0) \
 P(190, "keys", lvm_keys, 0) \
 P(192, "dig", lvm_dig, 0) \
 P(194, "cask", lvm_casknew, 0) \
 C(196, 5, "pour", lvm_bcopy, 0) \
 C(200, 3, "xlat", lvm_xlat, 0) \
 P(204, "two?", lvm_chainp, 0) \
 P(206, "string?", lvm_strp, 0) \
 P(208, "gem", lvm_gem, 0) \
 P(210, "gem?", lvm_gemp, 0) \
 P(212, "sin", lvm_sin, 0) \
 P(214, "cos", lvm_cos, 0) \
 P(216, "tan", lvm_tan, 0) \
 P(218, "atan", lvm_atan, 0) \
 C(220, 2, "atan2", lvm_atan2, 0) \
 P(224, "exp", lvm_exp, 0) \
 P(226, "sqrt", lvm_sqrt, 0) \
 P(228, "log", lvm_log, 0) \
 C(230, 2, "fpow", lvm_pow, 0) \
 C(234, 2, "twin", lvm_twin, 0) \
 P(238, "twin?", lvm_twinp, 0) \
 P(240, "re", lvm_re, 0) \
 P(242, "im", lvm_im, 0) \
 P(244, "conj", lvm_conj, 0) \
 P(246, "abs", lvm_abs, 0) \
 P(248, "arg", lvm_carg, 0) \
 C(250, 3, "tray", lvm_trayctor, 0) \
 P(254, "iota", lvm_iota, 0) \
 C(256, 3, "nif", lvm_nif, 0) \
 C(260, 4, "nifx", lvm_nifx, 0) \
 P(264, "rank", lvm_rank, 0) \
 P(266, "alen", lvm_alen, 0) \
 P(268, "shape", lvm_shape, 0) \
 P(270, "atype", lvm_atype, 0) \
 P(272, "asum", lvm_asum, 0) \
 P(274, "aprod", lvm_aprod, 0) \
 P(276, "amax", lvm_max, 0) \
 P(278, "amin", lvm_min, 0) \
 C(280, 2, "max", lvm_max2, 0) \
 C(284, 2, "min", lvm_min2, 0) \
 P(288, "aall", lvm_aall, 0) \
 P(290, "aany", lvm_aany, 0) \
 P(292, "floor", lvm_floor, 0) \
 C(294, 2, "inner", lvm_inner, 0) \
 C(298, 2, "outer", lvm_outer, 0) \
 P(302, "packp", lvm_packp, 0) \
 P(304, "sun?", lvm_sunp, 0) \
 P(306, "tray?", lvm_setp, 0) \
 P(308, "int", lvm_intf, 0) \
 P(310, "nom?", lvm_nomp, 0) \
 P(312, "name?", lvm_namep, 0) \
 P(314, "mint?", lvm_mintp, 0) \
 P(316, "tablet?", lvm_tabp, 0) \
 P(318, "charm?", lvm_charmp, 0) \
 P(320, "lit?", lvm_litp, 0) \
 P(322, "hot?", lvm_hotp, 0) \
 P(324, "nil?", lvm_nilp, 0) \
 P(326, "ev", lvm_eval, 0) \
 P(328, "call-cc", lvm_callk, 0) \
 C(330, 2, "scare", lvm_scare, 0) \
 P(334, "yield", lvm_yield_nif, 0) \
 C(336, 2, "twirl", lvm_twirl, 0) \
 P(340, "catch", lvm_wait, 0) \
 P(342, "rest", lvm_sleep, 0) \
 P(344, "landed?", lvm_donep, 0) \
 P(346, "scoop", lvm_scoop, 0) \
 P(348, "freeze", lvm_hush, 0) \
 P(350, "cue?", lvm_key, 0) \
 C(352, 3, "putbn", lvm_fputbn, 0) \
 P(356, "await", lvm_await, 0) \
 P(358, "see", lvm_fgetc, 0) \
 C(360, 2, "unsee", lvm_fungetc, 0) \
 P(364, "chug", lvm_chug, 0) \
 C(366, 2, "unchug", lvm_unchug, 0) \
 P(370, "inhand", lvm_inhand, 0) \
 C(372, 2, "put", lvm_fputc, 0) \
 C(376, 2, "say", lvm_fputs, 0) \
 P(380, "flush", lvm_fflush, 0) \
 P(382, "wheel", lvm_wheel, 0) \
 P(384, "turn", lvm_turn, 0) \
 P(386, "turnf", lvm_turnf, 0) \
 C(388, 2, "strike", lvm_coinmk, 0) \
 P(392, "load", lvm_load, 0) \
 P(394, "kind", lvm_kind, 0) \
 P(396, "coin?", lvm_coinp, 0) \
 P(398, "calloutdrive", lvm_calloutdrive, 0) \
 P(400, "reach-offset", lvm_reach_offset, 0) \
 P(402, "nat?", lvm_natp, 0) \
 P(404, "calloutresume", lvm_calloutresume, 0) \
 C(406, 3, "sits?", lvm_sitsp, 0) \
 C(410, 3, "subidx", lvm_subidx, 0) \
 P(414, "cats", lvm_cats, 0)
#define inst_rows(I) \
 I(lvm_unc) I(lvm_index) I(lvm_ret) I(lvm_ap) I(lvm_tap) I(lvm_apn) \
 I(lvm_tapn) I(lvm_jump) I(lvm_cond) I(lvm_arg) I(lvm_quote) I(lvm_defglob) \
 I(lvm_argap) I(lvm_quoteap) I(lvm_argtap) I(lvm_arg0) I(lvm_arg1) I(lvm_arg2) \
 I(lvm_arg3) I(lvm_quo0) I(lvm_quo1) I(lvm_quo2) I(lvm_quo3) I(lvm_quom1) \
 I(lvm_quom2) I(lvm_aa) I(lvm_aq) I(lvm_qa) I(lvm_qq) I(lvm_aap) \
 I(lvm_aqp) I(lvm_qap) I(lvm_qqp) I(lvm_argcap) I(lvm_argcup) I(lvm_argtwo) \
 I(lvm_argcond) I(lvm_argtwocond)
#define nif_run_p(at, nm, im, mod) { im }, { lvm_ret0 },
#define nif_run_c(at, a, nm, im, mod) { lvm_cur }, { .x = putcharm(a) }, { im }, { lvm_ret0 },
#define nif_def_p(at, nm, im, mod) { nm, { .k = nifs + at }, mod },
#define nif_def_c(at, a, nm, im, mod) nif_def_p(at, nm, im, mod)
#define nif_def_i(im) { #im, { .ap = im }, 0 },
#define nif_lvm_p(at, nm, im, mod) "(\"" nm "\" " #im ")"
#define nif_lvm_c(at, a, nm, im, mod) nif_lvm_p(at, nm, im, mod)
static union u const nifs[] = { nif_rows(nif_run_p, nif_run_c) };
static struct def const def1[] = { nif_rows(nif_def_p, nif_def_c) inst_rows(nif_def_i) };
char const nif_lvm[] = "(" nif_rows(nif_lvm_p, nif_lvm_c) ")";
#undef nif_rows
#undef inst_rows
#undef nif_run_p
#undef nif_run_c
#undef nif_def_p
#undef nif_def_c
#undef nif_def_i
#undef nif_lvm_p
#undef nif_lvm_c
