#!/bin/sh
# test/gate/libc.sh -- the LIBC differential: our own C library against the
# system's, function by function, with gcc+glibc as the second opinion.
#
# each test/libc/*.c is built twice -- once by mooncc, which pulls
# apps/moon/lib/nolibc.c by need, and once by gcc against glibc -- run, and the
# two OUTPUTS compared byte for byte. gcc is never trusted to be right, only to
# be a second opinion; where the standard leaves a choice (the magnitude of a
# comparison, an address, strerror's wording) the programs report the part that
# IS fixed, so a legitimate difference never fails the gate. see test/libc/say.h.
#
# ⚠ it compares OUTPUT, not the exit code the mooncc battery compares. an exit
# code is eight bits and says only THAT something drifted; a diff of the output
# names the function and the case. that is the whole reason this is its own gate
# and not more programs in test/cc.
#
# WHY IT EXISTS: the tree carries two libcs, and they drifted --
# nolibc's strtol wrapped on overflow where glibc saturates, so one source text
# read as two different numbers depending on which binary carried it. it went
# unnoticed because nothing gated the pure floor against anything. this is that
# gate, and it is rung 0 of for a reason: it is worth having whether
# or not the two libcs are ever merged.
#
# make owns the dependency graph; this owns the procedure.
# NOT set -e: the checks report their own failures with context.
#
# usage: libc.sh OUTDIR LOVE
set -u

ho=$1
m=$2
d=$ho/libc
mkdir -p "$d"

fail() { echo "FAIL test_libc: $*" >&2; exit 1; }
# the compiler under test: love's own mooncc verb (the crew layer, woken per invocation)
moonrun() { LOVE_NO_IMAGE= "$m" mooncc "$@"; }

arch=$(uname -m)
if [ "$arch" != x64 ]; then
  echo "test_libc: x86-64 only (mooncc emits x64), skipped on $arch"
  exit 0
fi
cc_g=$(command -v gcc || command -v cc) || true
if [ -z "${cc_g:-}" ]; then
  echo "test_libc: no system cc for the second opinion, skipped"
  exit 0
fi

n=0
fams=
for f in test/libc/*.c; do
  b=$(basename "$f" .c)

  moonrun -Itest/libc -o "$d/$b" "$f" > "$d/$b.build" 2>&1 \
    || { cat "$d/$b.build" >&2; fail "$b: mooncc could not build it"; }
  "$d/$b" > "$d/$b.ours" 2>&1
  ra=$?

  # -w: the battery is about the ANSWERS, and gcc warns about deliberate edges
  # (a snprintf that is meant to truncate, a memset of length 0)
  $cc_g -O0 -w -Itest/libc -o "$d/$b.g" "$f" 2> "$d/$b.gbuild" \
    || { cat "$d/$b.gbuild" >&2; fail "$b: the system cc could not build it"; }
  "$d/$b.g" > "$d/$b.theirs" 2>&1
  rg=$?

  [ $ra -eq $rg ] || fail "$b: exit ours $ra, $cc_g $rg"
  if ! cmp -s "$d/$b.ours" "$d/$b.theirs"; then
    echo "--- $b: ours vs $cc_g (first 20 differing lines) ---" >&2
    diff "$d/$b.theirs" "$d/$b.ours" 2>/dev/null | head -20 >&2
    fail "$b: our libc and the system's disagree"
  fi

  n=$((n + 1))
  fams="$fams $b"
done

[ $n -gt 0 ] || fail "no programs found in test/libc/"

# ---------------------------------------------------------------------------
# phase 2: the headers must not PROMISE what the library cannot deliver.
#
# every function apps/moon/include/{stdio,stdlib,string,ctype}.h declares is
# referenced by a generated program; a name with no definition anywhere fails
# the LINK and the gate says which. generated rather than listed, so it cannot
# rot as the headers grow -- adding a declaration and forgetting the body is
# exactly the failure this catches.
#
# it is a real failure mode, not a hypothetical: twelve names were declared with
# no body when this was first run (putchar puts fgetc getchar scanf isblank
# mempcpy rawmemchr reallocarray bsearch strtoll getprogname), so a program
# calling any of them built happily under gcc and died at the link under
# CC=mooncc. gnulib's progname module reaches getprogname exactly that way.
hdr=apps/moon/include
gen=$d/decls.c
# a declaration is a line STARTING with a lowercase type word and naming
# `ident(` -- which skips the #defines, the struct bodies and the extern data.
# the NAME is the identifier just before the first paren: cut the line there,
# then take what follows the last space or star. (matching the name in one
# regex is ambiguous -- the capture can slide onto a parameter.)
names=$(grep -hE '^[a-z][a-zA-Z_0-9 ]*[ *][a-z_][a-z_0-9]*\(' \
          "$hdr/stdio.h" "$hdr/stdlib.h" "$hdr/string.h" "$hdr/ctype.h" \
        | sed -E 's/\(.*//' | sed -E 's/.*[ *]//' | sort -u)
{
  echo '/* generated by test/gate/libc.sh -- do not edit */'
  echo '#include <stdio.h>'
  echo '#include <stdlib.h>'
  echo '#include <string.h>'
  echo '#include <ctype.h>'
  echo 'void *const __refs[] = {'
  for nm in $names; do echo "  (void *) $nm,"; done
  echo '  0 };'
  echo 'int main(void) { return __refs[0] == (void *) 1 ? 1 : 0; }'
} > "$gen"

nref=$(printf '%s\n' $names | grep -c .)
moonrun -o "$d/decls" "$gen" > "$d/decls.build" 2>&1 || {
  echo "--- the headers declare what nolibc does not define ---" >&2
  grep -i "undef" "$d/decls.build" >&2 || cat "$d/decls.build" >&2
  fail "header/library completeness: $nref names declared, at least one has no body"
}

echo "test_libc: nolibc agrees with $cc_g's libc over$fams ($n families), and defines all $nref names its headers declare"
