#ifndef _AI_INTTYPES_H
#define _AI_INTTYPES_H
/* freestanding inttypes for cc: the fixed-width types come from stdint, plus the
 * PRI format macros and the strtoimax/strtoumax conversions programs call. */
#include <stdint.h>

/* the PRI format macros, C99 7.8.1: an int-sized type takes no length, a long-sized one l,
   and the 64-bit ones are long here but long long on the 32-bit arm seats (whose intptr_t is
   a long, as stdint.h has it) */
#define PRId8      "d"
#define PRIi8      "i"
#define PRIo8      "o"
#define PRIu8      "u"
#define PRIx8      "x"
#define PRIX8      "X"
#define PRId16     "d"
#define PRIi16     "i"
#define PRIo16     "o"
#define PRIu16     "u"
#define PRIx16     "x"
#define PRIX16     "X"
#define PRId32     "d"
#define PRIi32     "i"
#define PRIo32     "o"
#define PRIu32     "u"
#define PRIx32     "x"
#define PRIX32     "X"
#define PRIdLEAST8 "d"
#define PRIiLEAST8 "i"
#define PRIoLEAST8 "o"
#define PRIuLEAST8 "u"
#define PRIxLEAST8 "x"
#define PRIXLEAST8 "X"
#define PRIdLEAST16"d"
#define PRIiLEAST16"i"
#define PRIoLEAST16"o"
#define PRIuLEAST16"u"
#define PRIxLEAST16"x"
#define PRIXLEAST16"X"
#define PRIdLEAST32"d"
#define PRIiLEAST32"i"
#define PRIoLEAST32"o"
#define PRIuLEAST32"u"
#define PRIxLEAST32"x"
#define PRIXLEAST32"X"
#define PRIdFAST8  "d"
#define PRIiFAST8  "i"
#define PRIoFAST8  "o"
#define PRIuFAST8  "u"
#define PRIxFAST8  "x"
#define PRIXFAST8  "X"
#ifdef __arm__
#define PRId64      "lld"
#define PRIi64      "lli"
#define PRIo64      "llo"
#define PRIu64      "llu"
#define PRIx64      "llx"
#define PRIX64      "llX"
#define PRIdLEAST64 "lld"
#define PRIiLEAST64 "lli"
#define PRIoLEAST64 "llo"
#define PRIuLEAST64 "llu"
#define PRIxLEAST64 "llx"
#define PRIXLEAST64 "llX"
#define PRIdFAST64  "lld"
#define PRIiFAST64  "lli"
#define PRIoFAST64  "llo"
#define PRIuFAST64  "llu"
#define PRIxFAST64  "llx"
#define PRIXFAST64  "llX"
#define PRIdMAX     "lld"
#define PRIiMAX     "lli"
#define PRIoMAX     "llo"
#define PRIuMAX     "llu"
#define PRIxMAX     "llx"
#define PRIXMAX     "llX"
#define PRIdFAST16  "d"
#define PRIiFAST16  "i"
#define PRIoFAST16  "o"
#define PRIuFAST16  "u"
#define PRIxFAST16  "x"
#define PRIXFAST16  "X"
#define PRIdFAST32  "d"
#define PRIiFAST32  "i"
#define PRIoFAST32  "o"
#define PRIuFAST32  "u"
#define PRIxFAST32  "x"
#define PRIXFAST32  "X"
#define PRIdPTR     "ld"
#define PRIiPTR     "li"
#define PRIoPTR     "lo"
#define PRIuPTR     "lu"
#define PRIxPTR     "lx"
#define PRIXPTR     "lX"
#else
#define PRId64      "ld"
#define PRIi64      "li"
#define PRIo64      "lo"
#define PRIu64      "lu"
#define PRIx64      "lx"
#define PRIX64      "lX"
#define PRIdLEAST64 "ld"
#define PRIiLEAST64 "li"
#define PRIoLEAST64 "lo"
#define PRIuLEAST64 "lu"
#define PRIxLEAST64 "lx"
#define PRIXLEAST64 "lX"
#define PRIdFAST64  "ld"
#define PRIiFAST64  "li"
#define PRIoFAST64  "lo"
#define PRIuFAST64  "lu"
#define PRIxFAST64  "lx"
#define PRIXFAST64  "lX"
#define PRIdMAX     "ld"
#define PRIiMAX     "li"
#define PRIoMAX     "lo"
#define PRIuMAX     "lu"
#define PRIxMAX     "lx"
#define PRIXMAX     "lX"
#define PRIdFAST16  "ld"
#define PRIiFAST16  "li"
#define PRIoFAST16  "lo"
#define PRIuFAST16  "lu"
#define PRIxFAST16  "lx"
#define PRIXFAST16  "lX"
#define PRIdFAST32  "ld"
#define PRIiFAST32  "li"
#define PRIoFAST32  "lo"
#define PRIuFAST32  "lu"
#define PRIxFAST32  "lx"
#define PRIXFAST32  "lX"
#define PRIdPTR     "ld"
#define PRIiPTR     "li"
#define PRIoPTR     "lo"
#define PRIuPTR     "lu"
#define PRIxPTR     "lx"
#define PRIXPTR     "lX"
#endif

typedef struct { intmax_t quot; intmax_t rem; } imaxdiv_t;

intmax_t  strtoimax(const char *, char **, int);
uintmax_t strtoumax(const char *, char **, int);
intmax_t  imaxabs(intmax_t);
imaxdiv_t imaxdiv(intmax_t, intmax_t);
#endif
